---
abstract: 'Solutions for L<< http://projecteuler.net >>'
author:
  - 'Adam Lesperance, C<< <lespea at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.22
  Test::More: 0.42
  Test::Most: 0.20
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Project-Euler
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0.00
  DateTime: 0.38
  DateTime::Format::DateParse: 0.00
  List::MoreUtils: 0.13
  List::Util: 1.20
  Math::Big: 1.12
  Modern::Perl: 1.03
  Moose: 0.65
  Moose::Role: 0.65
  Moose::Util::TypeConstraints: 0.65
  MooseX::Method::Signatures: 0.09
  MooseX::Types: 0.12
  autodie: 1.999
  perl: 5.10.0
  version: 0.77
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.001004
